default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  template: template0

development:
  <<: *default
  database: task01_development

test:
  <<: *default
  database: task01_test

production:
  <<: *default
  database: task01_production
  username: task01
  password: <%= ENV['TASK01_DATABASE_PASSWORD'] %>
